{% set name = "removestar" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a41405368f24d36b30051f07f940b723bf85bdcc228a93e07d1fc5a30447b6d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - removestar = removestar.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyflakes

test:
  imports:
    - removestar
  commands:
    - removestar --help

about:
  home: https://asmeurer.com/removestar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    removestar is a tool to automatically replace 'import *' in Python files with explicit imports.
  description: |
    removestar is a tool to automatically replace 'import *' in Python files with explicit imports.
  doc_url: https://asmeurer.com/removestar
  dev_url: https://github.com/asmeurer/removestar

extra:
  recipe-maintainers:
    - asmeurer
