{% set name = "removestar" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 526ba8ff609bcdeab02bf1194ac51cc96aa3d7d60dded63896ab2fd2a5a3ba13

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - removestar = removestar.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - pyflakes
    - nbformat
    - nbconvert

test:
  imports:
    - removestar
  commands:
    - removestar --help

about:
  home: https://asmeurer.com/removestar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    removestar is a tool to automatically replace 'import *' in Python files with explicit imports.
  description: |
    removestar is a tool to automatically replace 'import *' in Python files with explicit imports.
  doc_url: https://asmeurer.com/removestar
  dev_url: https://github.com/asmeurer/removestar

extra:
  recipe-maintainers:
    - asmeurer
    - Saransh-cpp
