{% set name = "removestar" %}
{% set version = "1.5.2" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 282d6dcb908a12b6dbf9c1050a04256f160e2de2c8bdea78a443dd547486fe3b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - removestar = removestar.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - pyflakes

test:
  imports:
    - removestar
  commands:
    - removestar --help

about:
  home: https://asmeurer.com/removestar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    removestar is a tool to automatically replace 'import *' in Python files with explicit imports.
  description: |
    removestar is a tool to automatically replace 'import *' in Python files with explicit imports.
  doc_url: https://asmeurer.com/removestar
  dev_url: https://github.com/asmeurer/removestar

extra:
  recipe-maintainers:
    - asmeurer
    - Saransh-cpp
