travis:
  secure:
    BINSTAR_TOKEN: kHcQv1Fge/x5UiLdowe2Jb0Yzfgoxn7VvrV8x03P11KIBZJOZOX0cipVtMsX4diqsbJmYxi6d6rw9TMCTKcUGk9kMkHDidzriZqUN/zGZ1kYTQUb6H+ic26428K+vhK+UszCKonciWphC2tm+VI4OP1G5P2vUyXM8Iynx9b2ieOr8ZQQmHLH88awSrbBqHzkSVxA//C0yXHb1llxLB3ok9fbVyLldJQglKa3Dpl+Wc4sj8GGc5XJngmrTvj+yd7ooOuKTUJ7IVvD4bfZfdNlybG49xxljC1q/mLcKaFn+0I6/5iheUmbIYeAFPDr18AL9WWurH8i8hMvs5QOVg1X2jjB6r1rCqzKmTKqvykhKlF4dnQduIV5ZXERKDwz2x/VIGMuj3GZhgh48M0+omBYzK8ax3u3YCnkySqSG39u3GRWkopVByEmjhh0tS8SnbWOIps6VnKdjl5+WF6iamIbsjDV/rRNXqqSBXGF3bT+Hq0oIhzhIzXRzx7TkEDk8k9g5+UkqS8hIBALYEKd+INwPMRGcouGXhImM4r/FLkInvOWOQudJQaM//0++oHF/W2rq3c/cuLtRf+L+unXnfyCEnxmcmzRae+RH0+lZDRLNb+/NvePkI13BIyeA+oB5gE01aWH71mzSvDpjTRZIwl8Ork99AqwNUkCc8e6usSx62Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
